from tkinter import *
from datetime import datetime
import time
f=open("password.txt","r")
x=f.read()
f.close()
f1=open("us1.txt","r")
use1=f1.read()
use1=use1.upper()
f1.close()
f2=open("us2.txt","r")
use2=f2.read()
use2=use2.upper()
f2.close()
f3=open("us3.txt","r")
use3=f3.read()
use3=use3.upper()
f3.close()
f4=open("us4.txt","r")
use4=f4.read()
use4=use4.upper()
f4.close()
t1="On the Insert tab, the galleries include items that are designed to coordinate\n with the overall look of your document. You can use these galleries to insert \ntables, headers, footers, lists, cover pages, and other document building \nblocks. When you create pictures, charts, or diagrams, they also coordinate \nwith your current document look. "
t2="To change the overall look of your document, choose new Theme elements \non the Page Layout tab. To change the looks available in the Quick Style \ngallery, use the Change Current Quick Style Set command. Both the \nThemes gallery and the Quick Styles gallery provide reset commands so that \nyou can always restore the look of your document to the original contained \nin your current template. "
p=0
ilist=[]
tx1="k;ajk d; saj; f; ajf ;akl sdfl asjj fak ;l sjk df;a ldfla; kjlf ds;j sa;kj fl;a jkf a;lks jf;a kjf d;aks da;ajjd sa;fl fkjfa ;fals djf;a; kaj; afkka ;lfj alfkk ;;af jaj k"
tx2="k;ajfjs ei akeij saiejkd sije djkdiek djiejdk die jd iejkdsla;;s i;akej dka ;klsd; ;aiek;ak diekd ie dk ie kdiekdiekkd diekeidlk d akdiei dkiejiejkd djdiekka dijdkkdjsiie k"
tx3="k;aa;lk eiu rjds fa;le lrui irur ajdk ieurjk duief djd fkuiejf fkjd fijea kjfalsu erjka durkd fje ijdsau ijad edjf eijksd ueij akudjk e aj;fdjs; lfiejkd fier jud jf ka ds sieka akja"
tx4="k;adkj; ajslk jdes rhr jkghg urk jk d;lak shgjk fdhkh hgjr url li djdkj fah;sk lsl kdhg jks ;ak lskjr uiek rjg hgha ;lks klks kkha kjah guri eurif jhgg ajk shgkj kghkg kukrk hdfu"
tx5="k;a;aldk gdhg utuu eiry thgh dfj kut ie ytiu eruhg eitu gyght yy tyt ygh djfk jakf hhut hue uryh jds khala ;;aj euyth jel ;;;d jhuty ete jjahj dsja hgfy tuy ehg iiytr gfj ukl;lkkjs"
tx6="k;aww;l weoej woej fdkk l;ao ;wie jsio uriu tyi hg jk lshfl akfjl sjf; kafeo oiwio uoeur tygh gja hjfj  f;ka  jk;g jksa heow irui utry owj fekw ojks jk so wwjske owiw o uw jlskslja "
tx7="k;aaqp qpwe ioro qoqp qipqr upq; aoip qpqpu erjf akf jawi urjt jgkh akfj apwu oqoro iui a;jklj a;jka kjal ;sfl kjpa pqu  prik ja;q pqpq pqk fkf js ssh qppq urjfj khgpq pqir urjgj "
tx8="k;aaq;oa jnvd nfjn vfj anvj fnv sri wur iqy thg nvnvn hdjs ksld nfh nrjv jjv nvgd jjf knvn djs nvd jvn skal kasjei wwqw nnv npqp wieun vais ndv nvna ;qpvn qiwe uvnv saj fdnv vnjvn"
tx9="k;aqpa ;p; qap lwokd cmc mv nfj cnmck djdfl dnvm nciv uemmnv mnc kdoi pekdk vn mcnv mn cie eiwwol lfn vmcn vmcno dkfk llcm kck mcmii ekkl; ammv mm vfk cmc ncns ksj aac mnvm cnd kns ncj"
tx10="k;asl, x,s, xkdb ,x,m, xmvb n,xbn mckdf kjgs kiu rprwe kxmn x,mvk sjwi ourwk fskc ,xmnbm xbv nxm ,v,cx jsjew mntm w,xo iv uiv uoi xiouv ,wmr nwrm nfsm nfx,x n,v mnvc nvjs nmm vxn,"
tx11="k;azz. .x,,x kmz, ,.x. z.xx ,aal ,cz., mkaj fkds mv,mzm v.z ,vc mxz,j akmv, .zm.v zm,. z., vmv ks jglm af. qmt, mrti ouo iy pyu lgkd fjg ksll; slmx .v., x,v; s; ldlk, xm.x, mvxm"
list=[]
z=0
def so(*arg):
	if(ask.get()=='1'):
		for m in range(len(tx1)):
			list.append(tx1[m])
		framea.pack_forget()
		frameaa.pack_forget()
		framell.pack()
		frameb.pack()
	if(ask.get()=='2'):
		for m in range(len(tx2)):
			list.append(tx2[m])
		frameaa.pack_forget()
		framea.pack_forget()
		framell.pack()
		frameb.pack()
	if(ask.get()=='3'):
		for m in range(len(tx3)):
			list.append(tx3[m])
		framea.pack_forget()
		frameaa.pack_forget()
		framell.pack()
		frameb.pack()
	if(ask.get()=='4'):
		for m in range(len(tx4)):
			list.append(tx4[m])
		framea.pack_forget()
		frameaa.pack_forget()
		framell.pack()
		frameb.pack()
	if(ask.get()=='5'):
		for m in range(len(tx5)):
			list.append(tx5[m])
		framea.pack_forget()
		framell.pack()
		frameaa.pack_forget()
		frameb.pack()
	if(ask.get()=='6'):
		for m in range(len(tx6)):
			list.append(tx6[m])
		framea.pack_forget()
		framell.pack()
		frameb.pack()
		frameaa.pack_forget()
	if(ask.get()=='7'):
		for m in range(len(tx7)):
			list.append(tx7[m])
		framea.pack_forget()
		framell.pack()
		frameaa.pack_forget()
		frameb.pack()
	if(ask.get()=='8'):
		for m in range(len(tx8)):
			list.append(tx8[m])
		framea.pack_forget()
		framell.pack()
		frameaa.pack_forget()
		frameb.pack()
	if(ask.get()=='9'):
		for m in range(len(tx9)):
			list.append(tx9[m])
		framea.pack_forget()
		frameaa.pack_forget()
		framell.pack()
		frameb.pack()
	if(ask.get()=='10'):
		for m in range(len(tx10)):
			list.append(tx10[m])
		framea.pack_forget()
		framell.pack()
		frameaa.pack_forget()
		frameb.pack()	
	if(ask.get()=='11'):
		for m in range(len(tx11)):
			list.append(tx11[m])
		frameaa.pack_forget()
		framea.pack_forget()
		framell.pack()
		frameb.pack()	
def s():
	frame3.pack_forget()
	framel.pack(pady=15)
	frameaa.pack()
	frametau.pack_forget()
	framenn.pack_forget()
	framecp.pack_forget()
	Ll.config(bg="indigo",fg="white")
	Test.config(bg="white",fg="black")
	Ru.config(bg="white",fg="black")
	Au.config(bg="white",fg="black")
	Cp.config(bg="white",fg="black")
def move():
	import time
	global z
	if(p<(len(list)-4)):
		if(ilist[p]==list[p-1]):
			z=z+1
			Tru.config(bg="blue",text="CORRECT",font="Trajan 20 bold",fg="white",pady=10,padx=40)
		else:
			z=z
			Tru.config(bg="red",text="WRONG",font="Trajan 20 bold",fg="white",pady=10,padx=55)
	else:
		if(p==(len(list)-4)):
			framel.pack_forget()
			k=(len(list))-4
			from datetime import datetime
			now=datetime.now()
			sec1=int(now.minute)*60+int(now.second)
			tim=sec1-sec
			gspeed=int((k/tim)*20)
			acc=((z*100)/(len(ilist)))
			nspeed=int((z/tim)*20)
			frame6=Frame(win,borderwidth=5,relief=RIDGE)
			x=time.asctime()
			name=Label(frame6,text="Name: "+(nam.get()).upper(),font="Trajan 16 bold",padx=300)
			name.grid(row=0,column=0)
			time=Label(frame6,text="Time:"+x,font="Trajan 16 bold")
			time.grid(row=1,column=0)
			gs=Label(frame6,text="Gross Speed:"+"%d"%gspeed,font="Trajan 16 bold")
			gs.grid(row=2,column=0)
			ac=Label(frame6,text="Accuracy:"+"%d"%acc+"%",font="Trajan 16 bold")
			ac.grid(row=3,column=0)
			ns=Label(frame6,text="Net Speed:"+"%d"%nspeed,font="Trajan 16 bold")
			ns.grid(row=4,column=0)
			frame6.pack()	
def go(*arg):
	global list
	global l
	global l1
	global l2
	global l3
	l.pack_forget()
	l1.pack_forget()
	l2.pack_forget()
	l3.pack_forget()
	Tru.pack()
	global str
	global p
	global ilist
	global sec
	ilist.append(en.get())
	en.delete(0,END)
	l=Label(framell,text=list[p],padx=30,pady=30,font="Trajan 20 bold",bg="green",fg="white")
	l.grid(row=0,column=0)
	l1=Label(framell,text=list[p+1],padx=30,pady=30,font="Trajan 20 bold")
	l1.grid(row=0,column=1)
	l2=Label(framell,text=list[p+2],padx=30,pady=30,font="Trajan 20 bold")
	l2.grid(row=0,column=2)
	l3=Label(framell,text=list[p+3],padx=30,pady=30,font="Trajan 20 bold")
	l3.grid(row=0,column=3)
	if(list[p]=='q'):
		qb.config(bg="blue",fg="white")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='w'):
		qb.config(bg="white",fg="black")
		wb.config(bg="blue",fg="white")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='e'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="blue",fg="white")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='r'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="blue",fg="white")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='t'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="blue",fg="white")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='y'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="blue",fg="white")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='u'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="blue",fg="white")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='i'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="blue",fg="white")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='o'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="blue",fg="white")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='p'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="blue",fg="white")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='p'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="blue",fg="white")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='a'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="blue",fg="white")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='s'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="blue",fg="white")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='d'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="blue",fg="white")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='f'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="blue",fg="white")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='g'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="blue",fg="white")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='h'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="blue",fg="white")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='j'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="blue",fg="white")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='k'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="blue",fg="white")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='l'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="blue",fg="white")
		col.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]==';'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="blue",fg="white")
		zb.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='z'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		zb.config(bg="blue",fg="white")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='x'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		xb.config(bg="blue",fg="white")
		zb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='c'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		cb.config(bg="blue",fg="white")
		xb.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='v'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		vb.config(bg="blue",fg="white")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='b'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		bb.config(bg="blue",fg="white")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='n'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		nb.config(bg="blue",fg="white")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='m'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		mb.config(bg="blue",fg="white")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]==','):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		com.config(bg="blue",fg="white")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]=='.'):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		full.config(bg="blue",fg="white")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		sp.config(bg="white",fg="black")
	if(list[p]==' '):
		qb.config(bg="white",fg="black")
		wb.config(bg="white",fg="black")
		eb.config(bg="white",fg="black")
		rb.config(bg="white",fg="black")
		tb.config(bg="white",fg="black")
		yb.config(bg="white",fg="black")
		ub.config(bg="white",fg="black")
		ib.config(bg="white",fg="black")
		ob.config(bg="white",fg="black")
		pb.config(bg="white",fg="black")
		ab.config(bg="white",fg="black")
		sb.config(bg="white",fg="black")
		db.config(bg="white",fg="black")
		fb.config(bg="white",fg="black")
		gb.config(bg="white",fg="black")
		hb.config(bg="white",fg="black")
		jb.config(bg="white",fg="black")
		kb.config(bg="white",fg="black")
		lb.config(bg="white",fg="black")
		col.config(bg="white",fg="black")
		full.config(bg="white",fg="black")
		xb.config(bg="white",fg="black")
		cb.config(bg="white",fg="black")
		vb.config(bg="white",fg="black")
		bb.config(bg="white",fg="black")
		nb.config(bg="white",fg="black")
		mb.config(bg="white",fg="black")
		com.config(bg="white",fg="black")
		zb.config(bg="white",fg="black")
		sp.config(bg="blue",fg="white")
	if(p==0):
		from datetime import datetime
		now=datetime.now()
		sec=int(now.minute)*60+int(now.second)
		if(ilist[0]=='a'):
			Tru.config(bg="blue",text="CORRECT",font="Trajan 20 bold",fg="white",pady=10,padx=40)
		else:
			Tru.config(bg="Red",text="WRONG",font="Trajan 20 bold",fg="white",pady=10,padx=55)
		p=p+1
	else:
		move()
		p=p+1
	framek1.pack()
	framek2.pack()
	framek3.pack()
	framek4.pack()
def n():
	framecp.pack_forget()
	frame3.pack()
	f=open("password.txt","w")
	f.write(ncp.get())
	f.close()
def cop():
	framek1.pack_forget()
	framek2.pack_forget()
	framek3.pack_forget()
	framek4.pack_forget()
	framel.pack_forget()
	frameaa.pack_forget()
	frametau.pack_forget()
	frame3.pack_forget()
	framenn.pack_forget()
	framecp.pack()
	Cp.config(bg="indigo",fg="white")
	Test.config(bg="white",fg="black")
	Ll.config(bg="white",fg="black")
	Au.config(bg="white",fg="black")
	Ru.config(bg="white",fg="black")
def ru2():
	if(nam.get().upper()==use1):
		f1=open("us1.txt","w")
		f1.write(nn.get().upper())
		f1.close()
	if(nam.get().upper()==use2):
		f2=open("us2.txt","w")
		f2.write(nn.get().upper())
		f2.close()
	if(nam.get().upper()==use3):
		f3=open("us3.txt","w")
		f3.write(nn.get().upper())
		f3.close()
	frametau.pack_forget()
	frame3.pack()
	framecp.pack_forget()
	framenn.pack_forget()
def ru():
	framek1.pack_forget()
	framek2.pack_forget()
	framek3.pack_forget()
	framek4.pack_forget()
	framel.pack_forget()
	Ru.config(bg="indigo",fg="white")
	Test.config(bg="white",fg="black")
	Ll.config(bg="white",fg="black")
	Au.config(bg="white",fg="black")
	Cp.config(bg="white",fg="black")
	frametau.pack_forget()
	frame3.pack_forget()
	framecp.pack_forget()
	framenn.pack()
	frameaa.pack_forget()
def tau():
	framek1.pack_forget()
	framek2.pack_forget()
	framek3.pack_forget()
	framek4.pack_forget()
	framel.pack_forget()
	frame3.pack_forget()
	framenn.pack_forget()
	framecp.pack_forget()
	frametau.pack()
	frameaa.pack_forget()
	Au.config(bg="indigo",fg="white")
	Test.config(bg="white",fg="black")
	Ru.config(bg="white",fg="black")
	Ll.config(bg="white",fg="black")
	Cp.config(bg="white",fg="black")
def gt():
	framek1.pack_forget()
	framek2.pack_forget()
	framek3.pack_forget()
	framek4.pack_forget()
	framel.pack_forget()
	framenn.pack_forget()
	frametau.pack_forget()
	framecp.pack_forget()
	frame3.pack()
	frameaa.pack_forget()
	Test.config(bg="indigo",fg="white")
	Ll.config(bg="white",fg="black")
	Ru.config(bg="white",fg="black")
	Au.config(bg="white",fg="black")
	Cp.config(bg="white",fg="black")
def window5(*arg):
	inp=data.get("1.0","end-1c")
	from datetime import datetime
	now=datetime.now()
	sec1=int(now.minute)*60+int(now.second)
	frame5.pack_forget()
	import time
	tim=sec1-sec2
	str=""
	lout=len(out)
	olist=[]
	for i in range(lout):
		ch=out[i]
		if(ch is not " "):
			str=str+ch
		else:
			olist.append(str)
			str=" "
	inp=inp+" "
	linp=len(inp)
	str1=""
	ilist=[]
	for i in range(linp):
		ch =inp[i]
		if(ch is not " "):
			str1=str1+ch
		else:
			ilist.append(str1)
			str1=" "
	z=0
	k=0
	if(len(ilist)<=len(olist)):	
		for i in range(len(ilist)):
			k=k+1
			if(olist[i]==ilist[i]):
				z=z+1
			else:
				z=z
	if(len(ilist)>len(olist)):	
		for i in range(len(olist)):
			k=k+1
			if(ilist[i]==olist[i]):
				z=z+1
			else:
				z=z
	gspeed=int((k/tim)*60)
	acc=((z*100)/(len(ilist)))
	nspeed=int((z/tim)*60)
	frame6=Frame(win,borderwidth=5,relief=RIDGE)
	x=time.asctime()
	name=Label(frame6,text="Name: "+(nam.get()).upper(),font="Trajan 16 bold",padx=300)
	name.grid(row=0,column=0)
	time=Label(frame6,text="Time:"+x,font="Trajan 16 bold")
	time.grid(row=1,column=0)
	gs=Label(frame6,text="Gross Speed:"+"%d"%gspeed,font="Trajan 16 bold")
	gs.grid(row=2,column=0)
	ac=Label(frame6,text="Accuracy:"+"%d"%acc+"%",font="Trajan 16 bold")
	ac.grid(row=3,column=0)
	ns=Label(frame6,text="Net Speed:"+"%d"%nspeed,font="Trajan 16 bold")
	ns.grid(row=4,column=0)
	exit=Button(frame6,text="Exit",font="TRAJAN 16 bold",padx=75,command=win.destroy)
	exit.grid(row=6,column=0)
	frame6.pack()
def td():
	global data
	global sec2
	from datetime import datetime
	data=Text(frame52,height=7,width=65,font="TRAJAN 16 bold")
	data.bind("<Return>",window5)
	data.grid(row=2,column=0)
	then=datetime.now()
	sec2=int(then.minute)*60+int(then.second)

def window4(*arg):
	global out
	if(tce.get()=='1'):
		out=t1
	if(tce.get()=='2'):
		out=t2	
	outp=Label(frame52,text=out,font="Trajan 16 bold")
	outp.grid(row=1,column=0)
	frame5.pack()
	frameh.pack_forget()
	frame3.pack_forget()
def win2(*arg):
	frame4=Frame(win,borderwidth=5,relief=RIDGE,bg="DodgerBlue")
	if((nam.get()).upper()==use1):
		if(pas.get()==x):
			print("Yes")
			frame5.pack_forget()
			frame2.pack_forget()
			frameh.pack(pady=15)
			frame3.pack()
		else:
			msg=Label(frame4,text="Sorry WRONG PASSWORD",font="TRAJAN 20 bold",bg="DodgerBlue",fg="White",pady=15,borderwidth=5,relief=RIDGE)
			msg.pack(fill=X)
			frame4.pack()
			frame2.pack_forget()
	elif((nam.get()).upper()==use2):
		if(pas.get()==x):
			print("Yes")
			frame5.pack_forget()
			frame2.pack_forget()
			frameh.pack(pady=15)
			frame3.pack()
		else:
			msg=Label(frame4,text="Sorry WRONG PASSWORD",font="TRAJAN 20 bold",bg="DodgerBlue",fg="White",pady=15,borderwidth=5,relief=RIDGE)
			msg.pack(fill=X)
			frame4.pack()
			frame2.pack_forget()
	elif((nam.get()).upper()==use3):
		if(pas.get()==x):
			print("Yes")
			frame5.pack_forget()
			frame2.pack_forget()
			frameh.pack(pady=15)
			frame3.pack()
		else:
			msg=Label(frame4,text="Sorry WRONG PASSWORD",font="TRAJAN 20 bold",bg="DodgerBlue",fg="White",pady=15,borderwidth=5,relief=RIDGE)
			msg.pack(fill=X)
			frame4.pack()
			frame2.pack_forget()
	elif((nam.get()).upper()==use4):
		if(pas.get()==x):
			print("Yes")
			frame5.pack_forget()
			frame2.pack_forget()
			frameh.pack(pady=15)
			frame3.pack()
		else:
			msg=Label(frame4,text="Sorry WRONG PASSWORD",font="TRAJAN 20 bold",bg="DodgerBlue",fg="White",pady=15,borderwidth=5,relief=RIDGE)
			msg.pack(fill=X)
			frame4.pack()
			frame2.pack_forget()
	else:
		if(pas.get()==x):
			print("Yes")
			frame5.pack_forget()
			frame2.pack_forget()
			frameh.pack(pady=15)
			framel.pack_forget()
			frame3.pack()
			f4=open("us4.txt","w")
			f4.write((nam.get()).upper())
			f4.close()
		else:
			msg=Label(frame4,text="Sorry WRONG PASSWORD",font="TRAJAN 20 bold",bg="DodgerBlue",fg="White",pady=15,borderwidth=5,relief=RIDGE)
			msg.pack(fill=X)
			frame4.pack()
			frame2.pack_forget()
win=Tk()
win.geometry("1200x700")
win.minsize(1200,700)
win.maxsize(1200,700)
win.configure(bg="DodgerBlue")
win.title("TYPING MASTER")
##window1
frame1=Frame(win,borderwidth=3,relief=RIDGE,bg="DodgerBlue")
frame1.pack()
Title=Label(frame1,padx=500,text="TYPING MASTER",bg="DodgerBlue",font="TRAJAN 20 bold",fg="White",pady=15)
Title.pack(fill=X)
frame2=Frame(win,borderwidth=2,relief=RIDGE,bg="DodgerBlue")
frame2.pack()
Name=Label(frame2,text="ENTER YOUR NAME",font="TRAJAN 14 bold",pady=10,bg="DodgerBlue",fg="white",padx=500)
Name.pack()
nam=StringVar()
uEntry=Entry(frame2,textvariable=nam,font="TRAJAN 14 bold",borderwidth=2,relief=RIDGE)
uEntry.pack()
Pas=Label(frame2,text="ENTER YOUR PASSWORD",font="TRAJAN 14 bold",pady=10,bg="DodgerBlue",fg="white")
Pas.pack()
pas=StringVar()
pEntry=Entry(frame2,textvariable=pas,font="TRAJAN 14 bold",show="*",borderwidth=2,relief=RIDGE)
pEntry.bind("<Return>",win2)
pEntry.pack()
#Window 2
frameh=Frame(win,borderwidth=3,relief=RIDGE,bg="DodgerBlue")
Ll=Button(frameh,text="Learn Lesson",bg="white",padx=25,font="TRAJAN 12 bold",command=s)
Ll.grid(row=0,column=0)
framel=Frame(win,borderwidth=3,relief=RIDGE,bg="orange")
frameaa=Frame(win,borderwidth=3,relief=RIDGE,bg="orange")
L1=Label(frameaa,text="1.PRIMARY KEYS \n2.Lesson with e and i key\n3.Lesson with r and u\n4.Lesson with g and h\n5.Lesson with t and y\n6.Lesson with w and o\n7.Lesson with q and p\n8.Lesson with n and v\n9.Lesson with c and m\n10.Lesson with x b and ,\n11.Lesson with z and .",font="TRAJAN 14 bold",pady=70,bg="indigo",fg="white",padx=30)
L1.pack()
framea=Frame(framel,borderwidth=3,relief=RIDGE,bg="orange")
framea.pack()
askl=Label(framea,text="Enter your lesson name",font="TRAJAN 14 bold",pady=10,bg="DodgerBlue",fg="white",padx=30)
askl.pack()
ask=Entry(framea,font="Trajan 16 bold")
ask.bind("<Return>",so)
ask.pack(pady=20)
framell=Frame(framel,borderwidth=3,relief=RIDGE,bg="orange")
frameb=Frame(framel,bg="orange")
l=Label(framell,text="a",padx=30,pady=30,font="Trajan 20 bold",bg="green",fg="white")
l.grid(row=0,column=0)	
l1=Label(framell,text="k",padx=30,pady=30,font="Trajan 20 bold")
l1.grid(row=0,column=1)	
l2=Label(framell,text=";",padx=30,pady=30,font="Trajan 20 bold")
l2.grid(row=0,column=2)
l3=Label(framell,text="a",padx=30,pady=30,font="Trajan 20 bold")
l3.grid(row=0,column=3)
en=Entry(frameb,font="Trajan 16 bold")
en.bind("<KeyRelease>",go)
en.pack(pady=20,side=BOTTOM)
framek1=Frame(win)
framek2=Frame(win)
framek3=Frame(win)
framek4=Frame(win)
qb=Button(framek1,text="q",font="TRAJAN 16 bold",pady=15,padx=20)
qb.grid(row=0,column=0)
wb=Button(framek1,text="w",font="TRAJAN 16 bold",pady=15,padx=20)
wb.grid(row=0,column=1)
eb=Button(framek1,text="e",font="TRAJAN 16 bold",pady=15,padx=20)
eb.grid(row=0,column=2)
rb=Button(framek1,text="r",font="TRAJAN 16 bold",pady=15,padx=20)
rb.grid(row=0,column=3)
tb=Button(framek1,text="t",font="TRAJAN 16 bold",pady=15,padx=20)
tb.grid(row=0,column=4)
yb=Button(framek1,text="y",font="TRAJAN 16 bold",pady=15,padx=20)
yb.grid(row=0,column=5)
ub=Button(framek1,text="u",font="TRAJAN 16 bold",pady=15,padx=20)
ub.grid(row=0,column=6)
ib=Button(framek1,text="i",font="TRAJAN 16 bold",pady=15,padx=20)
ib.grid(row=0,column=7)
ob=Button(framek1,text="o",font="TRAJAN 16 bold",pady=15,padx=20)
ob.grid(row=0,column=8)
pb=Button(framek1,text="p",font="TRAJAN 16 bold",pady=15,padx=20)
pb.grid(row=0,column=9)
ab=Button(framek2,text="a",font="TRAJAN 16 bold",pady=15,padx=20)
ab.grid(row=0,column=0)
sb=Button(framek2,text="s",font="TRAJAN 16 bold",pady=15,padx=20)
sb.grid(row=0,column=1)
db=Button(framek2,text="d",font="TRAJAN 16 bold",pady=15,padx=20)
db.grid(row=0,column=2)
fb=Button(framek2,text="f",font="TRAJAN 16 bold",pady=15,padx=20)
fb.grid(row=0,column=3)
gb=Button(framek2,text="g",font="TRAJAN 16 bold",pady=15,padx=20)
gb.grid(row=0,column=4)
hb=Button(framek2,text="h",font="TRAJAN 16 bold",pady=15,padx=20)
hb.grid(row=0,column=5)
jb=Button(framek2,text="j",font="TRAJAN 16 bold",pady=15,padx=20)
jb.grid(row=0,column=6)
kb=Button(framek2,text="k",font="TRAJAN 16 bold",pady=15,padx=20)
kb.grid(row=0,column=7)
lb=Button(framek2,text="l",font="TRAJAN 16 bold",pady=15,padx=20)
lb.grid(row=0,column=8)
col=Button(framek2,text=";",font="TRAJAN 16 bold",pady=15,padx=20)
col.grid(row=0,column=9)
zb=Button(framek3,text="z",font="TRAJAN 16 bold",pady=15,padx=20)
zb.grid(row=0,column=0)
xb=Button(framek3,text="x",font="TRAJAN 16 bold",pady=15,padx=20)
xb.grid(row=0,column=1)
cb=Button(framek3,text="c",font="TRAJAN 16 bold",pady=15,padx=20)
cb.grid(row=0,column=2)
vb=Button(framek3,text="v",font="TRAJAN 16 bold",pady=15,padx=20)
vb.grid(row=0,column=3)
bb=Button(framek3,text="b",font="TRAJAN 16 bold",pady=15,padx=20)
bb.grid(row=0,column=4)
nb=Button(framek3,text="n",font="TRAJAN 16 bold",pady=15,padx=20)
nb.grid(row=0,column=5)
mb=Button(framek3,text="m",font="TRAJAN 16 bold",pady=15,padx=20)
mb.grid(row=0,column=6)
com=Button(framek3,text=",",font="TRAJAN 16 bold",pady=15,padx=20)
com.grid(row=0,column=7)
full=Button(framek3,text=".",font="TRAJAN 16 bold",pady=15,padx=20)
full.grid(row=0,column=8)
sp=Button(framek4,text="SPACE",font="TRAJAN 16 bold",pady=15,padx=90)
sp.pack()
global Tru
Tru=Label(framel)
Test=Button(frameh,text="TEST",font="TRAJAN 12 bold",padx=50,bg="indigo",fg="white",command=gt)
Test.grid(row=0,column=1)
framenn=Frame(win,borderwidth=3,relief=RIDGE,bg="DodgerBlue")
Nam=Label(framenn,text="ENTER YOUR NAME",font="TRAJAN 14 bold",pady=10,bg="DodgerBlue",fg="white",padx=300)
Nam.pack()
nn=StringVar()
nu=Entry(framenn,textvariable=nn,font="TRAJAN 14 bold",borderwidth=2,relief=RIDGE)
nu.pack()
sub=Button(framenn,text="Next",font="TRAJAN 14 bold",borderwidth=2,relief=RIDGE,padx=30,bg="orange",command=ru2)
sub.pack()
Ru=Button(frameh,text="REPLACE USER",font="TRAJAN 12 bold",bg="white",padx=25,command=ru)
Ru.grid(row=0,column=2)
Cp=Button(frameh,text="CHANGE PASSWORD",font="TRAJAN 12 bold",bg="white",padx=20,command=cop)
Cp.grid(row=0,column=3)
Au=Button(frameh,text="ABOUT US",padx=25,font="TRAJAN 12 bold",bg="white",command=tau)
Au.grid(row=0,column=4)
frame3=Frame(win,borderwidth=3,relief=RIDGE,bg="DodgerBlue")
tc=Label(frame3,text="Enter your Test number",font="TRAJAN 14 bold",pady=10,bg="DodgerBlue",fg="white",padx=30)
tc.pack()
tce=Entry(frame3,font="Trajan 16 bold")
tce.bind("<Return>",window4)
tce.pack(pady=20)
framecp=Frame(win,borderwidth=3,relief=RIDGE,bg="DodgerBlue")
np=Label(framecp,text="ENTER YOUR NEW PASSWORD",font="TRAJAN 14 bold",pady=10,bg="DodgerBlue",fg="white",padx=300)
np.pack()
ncp=StringVar()
pa=Entry(framecp,textvariable=ncp,font="TRAJAN 14 bold",borderwidth=2,relief=RIDGE,show="*")
pa.pack()
subp=Button(framecp,text="Next",font="TRAJAN 14 bold",borderwidth=2,relief=RIDGE,padx=30,bg="orange",command=n)
subp.pack()
frametau=Frame(win,borderwidth=3,relief=RIDGE,bg="DodgerBlue")
lau=Label(frametau,text="It is my first project-Ankit kumar",font="TRAJAN 14 bold",pady=10,bg="DodgerBlue",fg="white")
lau.pack()
#Window 3
frame5=Frame(win,borderwidth=2,relief=RIDGE,bg="DodgerBlue")
frame51=Frame(frame5,bg="DodgerBlue")
frame51.pack()
back=Button(frame51,text="Back",font="TRAJAN 16 bold",padx=75,command=win2)
back.grid(row=0,column=0,padx=70)
start=Button(frame51,text="Start",font="TRAJAN 16 bold",padx=75,command=td)
start.grid(row=0,column=1,padx=70)
frame52=Frame(frame5,bg="DodgerBlue")
frame52.pack()	
win.mainloop()